### ISSUE TITLE
Triangles output has a length of 0 when using RestoreBoundary and ConstrainEdges

### ISSUE THREAD

**Issue by anzago** [andywiecko/BurstTriangulator#105]
Hi,

I'm using BurstTriangulator to create meshes from large water polygons. 
Everything works well when I render simple areas that have like 4-5-6 edges, but for more complex zones in the port (thousands of edges), I get a strange result : the output triangle array has a length of 0 and `triangulator.Output.Status.Value` is OK.

The strangest part is that if I put a breakpoint inside `DelaunayTriangulationJob.Execute()` and just press play when it's hit then I get a valid triangle output and the mesh renders perfectly in Unity.
This feels like a race condition problem but looking at the Triangulator code and how jobs works, this feels unlikely 😅.
Also, the problem does not happen if I don't use the RestoreBoundary/ConstrainEdges settings.

Here is how I call the triangulator : 
```C#
private Triangulator triangulate(float2[] positions)
    {
        int[] constraintIndices = new int[2 * positions.Length];

        for (int i = 1, j = 1; i < positions.Length; ++i)
        {
            constraintIndices[j] = i;
            constraintIndices[j + 1] = i;
            j += 2;
        }

        constraintIndices[0] = 0;
        constraintIndices[^1] = 0;
        
        using var finalPositions = new NativeArray<float2>(positions, Allocator.Persistent);
        
        using var constraintEdges = new NativeArray<int>(constraintIndices, Allocator.Persistent);

        var triangulator = new Triangulator(capacity: 8192, Allocator.Persistent)
        {
            Input =
            {
                Positions = finalPositions,
                ConstraintEdges = constraintEdges
            },
            Settings =
            {
                RestoreBoundary = true,
                ConstrainEdges = true,
                ValidateInput = true,
            }
        };
        
        JobHandle job = triangulator.Schedule();
        job.Complete();
        
        Debug.Log(triangulator.Output.Triangles.Length);
        Debug.Log(triangulator.Output.Status.Value);
        Debug.Log(job.IsCompleted);
        
        return triangulator;
    }
```

This outputs in debug console : 0 / OK / True

Do you have any idea like something I did wrong or where it could come from ?

Thankful for any advice !

Best regards,

Anthony

**Comment by anzago** [comment]
Here are the positions serialized in json [positions.json](https://github.com/andywiecko/BurstTriangulator/files/14049668/positions.json)

Thanks for answering this fast btw !

Anthony

**Comment by andywiecko** [comment]
No problem 🙂

Thanks for the data! I will try to debug the input as fast as I can, probably during the upcoming weekend.

Best,
Andrzej

**Comment by andywiecko** [comment]
Hi Anthony,

I finally found time to investigate the issue with your data. After debugging, surprisingly, I discovered that commenting out the `BurstCompile` attribute in the `DelaunayTriangulationJob` eliminates the bug, and triangulation performs correctly. It's rather strange; it suggests that either `Burst` has an internal bug during compilation (I've updated it to the latest `1.8.12`) or the `delanuator` port has some issues. 

![image](https://github.com/andywiecko/BurstTriangulator/assets/15237586/d57a0c21-ff17-46f6-8e49-83e8c12b473d)

Nevertheless, many thanks for reporting the issue. I will try to fix this, and I will let you know in the next message about the potential fix.


Best,
Andrzej

**Comment by anzago** [comment]
Hi @andywiecko !

Don't worry about the time it takes !
I could shift to other features the last few weeks. Recently I copied your code in my project and commented out the attribute and it works with acceptable performance !

Thanks again for your commitment 😄

**Comment by andywiecko** [comment]
Hi @anzago,
I've finally found some time to do proper debugging. I apologize for the delay.

---

I have great news! I've found what is causing the problem. It turns out that although the planting seed algorithm is correctly implemented, there were issues with floating-point precision, leading to a bad triangulation result:

![image](https://github.com/andywiecko/BurstTriangulator/assets/15237586/0e1b39b6-26b4-4245-9a10-8a9b7ca7a527)

After changing from `float2` to `double2`, it triangulates correctly and we obtain the desired result:

![image](https://github.com/andywiecko/BurstTriangulator/assets/15237586/efee07ce-226d-4ae9-82ba-df8aa7a4fdac)

I'm going to prepare a new release next week which will fix this issue.

**Comment by andywiecko** [comment]
Hi @anzago,
I apologize for the delay. There's a lot happening with the package, and some exciting features are on the way!

I think that soon there will be release `v3` which will handle `double2`/`float2`/`int2` coordinates, but it might take some time, possibly a few months (1-3). In the meantime, I've pushed a [branch](https://github.com/andywiecko/BurstTriangulator/compare/experimental/double2-coords) with [commit](https://github.com/andywiecko/BurstTriangulator/commit/005724ae874501afabf99d5e317042fb038f5f5f) that makes a simple replacement of `float2` with `double2`, allowing your example to run without errors.

I hope this will help. I'll keep you updated once the feature is released.

Best,
Andrzej

**Comment by andywiecko** [comment]
Hi @anzago,

Recently, I've managed to release version [**`v3`**](https://github.com/andywiecko/BurstTriangulator/releases/tag/v3.0.0), which resolves your issue.
Triangulator is now based on `double2`.
I added commit 233a978 with a test to check this particular issue.

Best,
Andrzej

---

PS Appologies for the delay!
