### ISSUE TITLE
Tests fail to compile when using .net standard 2.1 api compatibility level

### ISSUE THREAD

**Issue by HalfVoxel** [andywiecko/BurstTriangulator#228]
Or it might be when changing to use IL2CPP.

![bild](https://github.com/user-attachments/assets/51603b6d-33b8-4ad9-be4e-aea2ef674302)
![bild](https://github.com/user-attachments/assets/9c679046-8c26-4b6e-9976-9c7bd777c6da)

This seems to be related to usages of `dynamic` variables.

**Comment by HalfVoxel** [comment]
This compilation error happened in the unity editor.

**Comment by andywiecko** [comment]
@HalfVoxel you have to provide me some more details to your issue, since it works on my machine and CI.

![image](https://github.com/user-attachments/assets/05ab34f6-00ce-4a71-9106-e16eb846837f)

Which Unity version are you using?

**Comment by HalfVoxel** [comment]
I'm using Unity 6000.0.12f1.

Could definitely be a Unity bug, I guess.
Have you tried doing a build with code that is actively using the `dynamic` code paths?

**Comment by andywiecko** [comment]
> Could definitely be a Unity bug, I guess.

I see...

Once Unity 6 exits preview, I’ll definitely add tests for this in the pipeline, especially now that CI is properly configured.
If you manage to resolve your issue, please let me know.

Best,
Andrzej

**Comment by HalfVoxel** [comment]
Let's revisit later, then. This issue is not blocking for me personally.
