### ISSUE TITLE
possible leak

### ISSUE THREAD

**Issue by DusanPaulovic** [andywiecko/BurstTriangulator#250]
ignoredHalfedgesForPlantingSeeds don't get disposed in the Triangulator.Dispose method

**Comment by andywiecko** [comment]
Hi @DusanPaulovic,
Thank you for reporting this! I’ve already fixed it in commit da5be93ad985fa51fd0cb89a9c80227a59c47663. Fortunately, it was resolved before the release with `IgnoredHalfedgesForPlantingSeeds`. :)

**Comment by andywiecko** [comment]
P.S. In commit 03d7713eb16c5052326a13f942c721faeb087946, I added a test to check proper disposal of Triangulator data. Hopefully, this will prevent similar bugs from being introduced in the future!
