### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [andywiecko/BurstTriangulator#29]
Hey there,
    You will have to forgive me if this is a silly question, but I started a venture down an unfamiliar path and I am investigating options. Do you think there could be any success using this against a heightmap to lay out the points in 2d space, then taking them and applying height to them to form a 3d mesh? I was thinking that, perhaps, the color variation could affect the point density in preparation for height variation, or something along those lines.

Mostly because it was something I never tried before, I have been testing out different ways to go about trying to create mesh, but have been unsatisfied with the results so far, as well as the performance, so I was hoping that this might be useful in that regard, but just wanted to check before I dove into it if my thought process is headed in a usable direction, to begin with.

Thanks,
-MH

**Comment by andywiecko** [comment]
Hi @MostHated,
thanks for the feedback!

> Do you think there could be any success using this against a heightmap to lay out the points in 2d space, then taking them and applying height to them to form a 3d mesh? I was thinking that, perhaps, the color variation could affect the point density in preparation for height variation, or something along those lines.

I think that as long as one can find function $f: \mathbb R^2 \to \mathbb R^3$ for the input data, then triangulation is a relatively simple task. In other words, there must be some projection plane where points are not degenerated (distinct collection).
One could define some normal $n$ and use the dot product to project $\mathbb R^3$ to $\mathbb R^2$.

I prepare a small demo for you. It generates 512 randomly distribute points in $\mathbb R^3$ and then projects them to $\mathbb R^2$ by just taking _xz_ components.
My demo could be extended to fit data into the "rectangle" by adding corner points and 4 constrained (boundary) edges. If you are interested in this I could help with that too.
Additionally, the mesh itself could be created in the job as well if performance is required (see [the details](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/Mesh.MeshData.html)).

https://user-images.githubusercontent.com/15237586/201515118-3ed7da95-1c2d-42b2-8e8b-78c433295952.mp4

Here is the code:

```csharp
using andywiecko.BurstTriangulator;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class Demo : MonoBehaviour
{
    [SerializeField]
    private float3 bounds = math.float3(20, 5, 20f);

    [SerializeField]
    private int samples = 512;

    public void Start()
    {
        var random = new Unity.Mathematics.Random(seed: 4353453);
        using var positions = new NativeArray<float3>(samples, Allocator.Persistent);
        using var projectedPositions = new NativeArray<float2>(samples, Allocator.Persistent);
        using var triangulator = new Triangulator(capacity: samples * samples, Allocator.Persistent)
        {
            Input =
            {
                Positions = projectedPositions,
            },
            Settings =
            {
                ValidateInput = true,
                UseLocalTransformation = true,
                RefineMesh = false,
                ConstrainEdges = false,
                RestoreBoundary = false,
            }
        };

        var dependencies = new JobHandle();
        dependencies = new GeneratePositions(positions, random, bounds).Schedule(dependencies);
        dependencies = new ProjectPositionsJob(positions, projectedPositions).Schedule(samples, innerloopBatchCount: 64, dependencies);
        dependencies = triangulator.Schedule(dependencies);
        dependencies.Complete();

        var mesh = new Mesh();
        mesh.Clear();
        mesh.SetVertices(positions.Reinterpret<float3, Vector3>().ToArray());
        mesh.SetTriangles(triangulator.Output.Triangles.ToArray(), submesh: 0);
        mesh.RecalculateNormals();
        mesh.RecalculateBounds();
        var meshFilter = GetComponent<MeshFilter>();
        meshFilter.mesh = mesh;
    }

    [BurstCompile]
    private struct GeneratePositions : IJob
    {
        private NativeArray<float3> positions;
        private Unity.Mathematics.Random random;
        private readonly float3 bounds;

        public GeneratePositions(NativeArray<float3> positions, Unity.Mathematics.Random random, float3 bounds)
        {
            this.positions = positions;
            this.random = random;
            this.bounds = bounds;
        }

        public void Execute()
        {
            for (int i = 0; i < positions.Length; i++)
            {
                Execute(i);
            }
        }

        private void Execute(int i)
        {
            positions[i] = bounds * random.NextFloat3();
        }
    }

    [BurstCompile]
    private struct ProjectPositionsJob : IJobParallelFor
    {
        private NativeArray<float3>.ReadOnly positions;
        private NativeArray<float2> projectedPositions;

        public ProjectPositionsJob(NativeArray<float3> positions, NativeArray<float2> projectedPositions)
        {
            this.positions = positions.AsReadOnly();
            this.projectedPositions = projectedPositions;
        }

        public void Execute(int i)
        {
            projectedPositions[i] = positions[i].xz;
        }
    }
}
```

I hope that I understand your question correctly and this answered your question. If you have any additional questions let me know.

Best, 
Andrzej

**Comment by MostHated** [comment]
This is great, I very much appreciate the demonstration/example. I am going to do some experimentation with it and see what I can come up with. :+1:
